from typing import Any, Dict, Optional

class MP4:
    tags: Optional[Dict[str, Any]]

    def __init__(self, filename: str) -> None: ...
    def save(self) -> None: ...
    def add_tags(self) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...

class MP4Cover(bytes):
    FORMAT_JPEG: int
    FORMAT_PNG: int

    def __new__(cls, data: bytes, imageformat: int = FORMAT_JPEG) -> "MP4Cover": ...
